In [23]:
from datetime import datetime
import json
import sys
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath("/Users/zeyaddaowd/Desktop/GP/LedgerDB/aml_service/notebooks/exploration.ipynb"))) # two dirname to get to aml_service path 
    
with open(os.path.join(BASE_DIR, 'config', 'thresholds.json')) as f:
    THRESHOLDS = json.load(f)
sys.path.append(BASE_DIR)

from graph.builder import TransactionsGraph

In [24]:
csv_path = "/Users/zeyaddaowd/Desktop/GP/LedgerDB/aml_service/IBM/amlWORLD/HI-Small_Trans.csv"

In [25]:
import pandas as pd

In [26]:
df = pd.read_csv(csv_path)

In [28]:
df.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [29]:
print("From Bank NaNs:", df["From Bank"].isna().sum())
print("Account NaNs:", df["Account"].isna().sum())
print("To Bank NaNs:", df["To Bank"].isna().sum())
print("Account.1 NaNs:", df["Account.1"].isna().sum())

From Bank NaNs: 0
Account NaNs: 0
To Bank NaNs: 0
Account.1 NaNs: 0

In [30]:
df["From_Account"] = (
    df["From Bank"].astype("string")
    .str.cat(df["Account"].astype("string"), sep="_")
)
df["To_Account"] = (
    df["To Bank"].astype("string")
    .str.cat(df["Account.1"].astype("string"), sep="_")
)

In [31]:
all_accounts = set(df["From_Account"]).union(set(df["To_Account"]))
print("Total unique accounts:", len(all_accounts))

Total unique accounts: 515088

In [8]:
df.drop(columns=["From Bank", "Account", "To Bank", "Account.1"], inplace=True)

In [9]:
df.head()

,Timestamp,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering,From_Account,To_Account
0,2022/09/01 00:20,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0,10_8000EBD30,10_8000EBD30
1,2022/09/01 00:20,0.01,US Dollar,0.01,US Dollar,Cheque,0,3208_8000F4580,1_8000F5340
2,2022/09/01 00:00,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0,3209_8000F4670,3209_8000F4670
3,2022/09/01 00:02,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0,12_8000F5030,12_8000F5030
4,2022/09/01 00:06,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0,10_8000F5200,10_8000F5200

In [10]:
print(df["Payment Format"].unique())

['Reinvestment' 'Cheque' 'Credit Card' 'ACH' 'Cash' 'Wire' 'Bitcoin']

In [11]:
## print 10 rows where Payment Format
for payment_format in df["Payment Format"].unique():
    print(payment_format)
    #print(df[df["Payment Format"] == payment_format].head(2))
    mask = df["Payment Format"] == payment_format
    all_same = (
        df.loc[mask, "From_Account"]
        == df.loc[mask, "To_Account"]
    ).all()

    print(f"{payment_format}: {all_same}")

Reinvestment
Reinvestment: True
Cheque
Cheque: False
Credit Card
Credit Card: False
ACH
ACH: False
Cash
Cash: False
Wire
Wire: False
Bitcoin
Bitcoin: False

In [12]:
print(df["Payment Currency"].unique())

['US Dollar' 'Bitcoin' 'Euro' 'Australian Dollar' 'Yuan' 'Rupee' 'Yen'
 'Mexican Peso' 'UK Pound' 'Ruble' 'Canadian Dollar' 'Swiss Franc'
 'Brazil Real' 'Saudi Riyal' 'Shekel']

In [13]:
currency_exchange = {
    "US Dollar": 52,
    "Bitcoin": 3314084,
    "Euro": 60,
    "Australian Dollar": 36.5,
    "Yuan": 7.67,
    "Rupee": 0.55,
    "Yen": 0.32,
    "Mexican Peso": 3,
    "UK Pound": 69.75,
    "Ruble": 0.72,
    "Canadian Dollar": 37.19,
    "Swiss Franc": 65.27,
    "Brazil Real": 10.24,
    "Saudi Riyal": 13.84,
    "Shekel": 17.8
}

In [ ]:
df["Amount_Paid_EGP"] = df.apply(
    lambda row: row["Amount Paid"] * currency_exchange[row["Payment Currency"]],
    axis=1
)

In [15]:
## nans in amount EGP
print("Amount Paid (EGP) NaNs:", df["Amount Paid (EGP)"].isna().sum())

Amount Paid (EGP) NaNs: 0

In [16]:
## convert Timestamp to datetime
df["Timestamp"] = pd.to_datetime(df["Timestamp"])
print(df["Timestamp"].dtype)

datetime64[ns]

In [17]:
print(max(df["Timestamp"]))
print(min(df["Timestamp"]))
print(df["Timestamp"].max() - df["Timestamp"].min())

2022-09-18 16:18:00
2022-09-01 00:00:00
17 days 16:18:00

In [18]:
print(len(df))

5078345

In [19]:
graph = TransactionsGraph()

for index, row in df.iterrows():
    if index % 10000 == 0:
        print(f"Processing transaction {index} / {len(df)}")
    graph.add_transaction(from_account=row["From_Account"], to_account=row["To_Account"], amount=row["Amount Paid (EGP)"], timestamp=row["Timestamp"])

Processing transaction 0 / 5078345
Processing transaction 10000 / 5078345
Processing transaction 20000 / 5078345
Processing transaction 30000 / 5078345
Processing transaction 40000 / 5078345
Processing transaction 50000 / 5078345
Processing transaction 60000 / 5078345
Processing transaction 70000 / 5078345
Processing transaction 80000 / 5078345
Processing transaction 90000 / 5078345
Processing transaction 100000 / 5078345
Processing transaction 110000 / 5078345
Processing transaction 120000 / 5078345
Processing transaction 130000 / 5078345
Processing transaction 140000 / 5078345
Processing transaction 150000 / 5078345
Processing transaction 160000 / 5078345
Processing transaction 170000 / 5078345
Processing transaction 180000 / 5078345
Processing transaction 190000 / 5078345
Processing transaction 200000 / 5078345
Processing transaction 210000 / 5078345
Processing transaction 220000 / 5078345
Processing transaction 230000 / 5078345
Processing transaction 240000 / 5078345
Processing transaction 250000 / 5078345
Processing transaction 260000 / 5078345
Processing transaction 270000 / 5078345
Processing transaction 280000 / 5078345
Processing transaction 290000 / 5078345
Processing transaction 300000 / 5078345
Processing transaction 310000 / 5078345
Processing transaction 320000 / 5078345
Processing transaction 330000 / 5078345
Processing transaction 340000 / 5078345
Processing transaction 350000 / 5078345
Processing transaction 360000 / 5078345
Processing transaction 370000 / 5078345
Processing transaction 380000 / 5078345
Processing transaction 390000 / 5078345
Processing transaction 400000 / 5078345
Processing transaction 410000 / 5078345
Processing transaction 420000 / 5078345
Processing transaction 430000 / 5078345
Processing transaction 440000 / 5078345
Processing transaction 450000 / 5078345
Processing transaction 460000 / 5078345
Processing transaction 470000 / 5078345
Processing transaction 480000 / 5078345
Processing transaction 490000 / 5078345
Processing transaction 500000 / 5078345
Processing transaction 510000 / 5078345
Processing transaction 520000 / 5078345
Processing transaction 530000 / 5078345
Processing transaction 540000 / 5078345
Processing transaction 550000 / 5078345
Processing transaction 560000 / 5078345
Processing transaction 570000 / 5078345
Processing transaction 580000 / 5078345
Processing transaction 590000 / 5078345
Processing transaction 600000 / 5078345
Processing transaction 610000 / 5078345
Processing transaction 620000 / 5078345
Processing transaction 630000 / 5078345
Processing transaction 640000 / 5078345
Processing transaction 650000 / 5078345
Processing transaction 660000 / 5078345
Processing transaction 670000 / 5078345
Processing transaction 680000 / 5078345
Processing transaction 690000 / 5078345
Processing transaction 700000 / 5078345
Processing transaction 710000 / 5078345
Processing transaction 720000 / 5078345
Processing transaction 730000 / 5078345
Processing transaction 740000 / 5078345
Processing transaction 750000 / 5078345
Processing transaction 760000 / 5078345
Processing transaction 770000 / 5078345
Processing transaction 780000 / 5078345
Processing transaction 790000 / 5078345
Processing transaction 800000 / 5078345
Processing transaction 810000 / 5078345
Processing transaction 820000 / 5078345
Processing transaction 830000 / 5078345
Processing transaction 840000 / 5078345
Processing transaction 850000 / 5078345
Processing transaction 860000 / 5078345
Processing transaction 870000 / 5078345
Processing transaction 880000 / 5078345
Processing transaction 890000 / 5078345
Processing transaction 900000 / 5078345
Processing transaction 910000 / 5078345
Processing transaction 920000 / 5078345
Processing transaction 930000 / 5078345
Processing transaction 940000 / 5078345
Processing transaction 950000 / 5078345
Processing transaction 960000 / 5078345
Processing transaction 970000 / 5078345
Processing transaction 980000 / 5078345
Processing transaction 990000 / 5078345
Processing transaction 1000000 / 5078345
Processing transaction 1010000 / 5078345
Processing transaction 1020000 / 5078345
Processing transaction 1030000 / 5078345
Processing transaction 1040000 / 5078345
Processing transaction 1050000 / 5078345
Processing transaction 1060000 / 5078345
Processing transaction 1070000 / 5078345
Processing transaction 1080000 / 5078345
Processing transaction 1090000 / 5078345
Processing transaction 1100000 / 5078345
Processing transaction 1110000 / 5078345
Processing transaction 1120000 / 5078345
Processing transaction 1130000 / 5078345
Processing transaction 1140000 / 5078345
Processing transaction 1150000 / 5078345
Processing transaction 1160000 / 5078345
Processing transaction 1170000 / 5078345
Processing transaction 1180000 / 5078345
Processing transaction 1190000 / 5078345
Processing transaction 1200000 / 5078345
Processing transaction 1210000 / 5078345
Processing transaction 1220000 / 5078345
Processing transaction 1230000 / 5078345
Processing transaction 1240000 / 5078345
Processing transaction 1250000 / 5078345
Processing transaction 1260000 / 5078345
Processing transaction 1270000 / 5078345
Processing transaction 1280000 / 5078345
Processing transaction 1290000 / 5078345
Processing transaction 1300000 / 5078345
Processing transaction 1310000 / 5078345
Processing transaction 1320000 / 5078345
Processing transaction 1330000 / 5078345
Processing transaction 1340000 / 5078345
Processing transaction 1350000 / 5078345
Processing transaction 1360000 / 5078345
Processing transaction 1370000 / 5078345
Processing transaction 1380000 / 5078345
Processing transaction 1390000 / 5078345
Processing transaction 1400000 / 5078345
Processing transaction 1410000 / 5078345
Processing transaction 1420000 / 5078345
Processing transaction 1430000 / 5078345
Processing transaction 1440000 / 5078345
Processing transaction 1450000 / 5078345
Processing transaction 1460000 / 5078345
Processing transaction 1470000 / 5078345
Processing transaction 1480000 / 5078345
Processing transaction 1490000 / 5078345
Processing transaction 1500000 / 5078345
Processing transaction 1510000 / 5078345
Processing transaction 1520000 / 5078345
Processing transaction 1530000 / 5078345
Processing transaction 1540000 / 5078345
Processing transaction 1550000 / 5078345
Processing transaction 1560000 / 5078345
Processing transaction 1570000 / 5078345
Processing transaction 1580000 / 5078345
Processing transaction 1590000 / 5078345
Processing transaction 1600000 / 5078345
Processing transaction 1610000 / 5078345
Processing transaction 1620000 / 5078345
Processing transaction 1630000 / 5078345
Processing transaction 1640000 / 5078345
Processing transaction 1650000 / 5078345
Processing transaction 1660000 / 5078345
Processing transaction 1670000 / 5078345
Processing transaction 1680000 / 5078345
Processing transaction 1690000 / 5078345
Processing transaction 1700000 / 5078345
Processing transaction 1710000 / 5078345
Processing transaction 1720000 / 5078345
Processing transaction 1730000 / 5078345
Processing transaction 1740000 / 5078345
Processing transaction 1750000 / 5078345
Processing transaction 1760000 / 5078345
Processing transaction 1770000 / 5078345
Processing transaction 1780000 / 5078345
Processing transaction 1790000 / 5078345
Processing transaction 1800000 / 5078345
Processing transaction 1810000 / 5078345
Processing transaction 1820000 / 5078345
Processing transaction 1830000 / 5078345
Processing transaction 1840000 / 5078345
Processing transaction 1850000 / 5078345
Processing transaction 1860000 / 5078345
Processing transaction 1870000 / 5078345
Processing transaction 1880000 / 5078345
Processing transaction 1890000 / 5078345
Processing transaction 1900000 / 5078345
Processing transaction 1910000 / 5078345
Processing transaction 1920000 / 5078345
Processing transaction 1930000 / 5078345
Processing transaction 1940000 / 5078345
Processing transaction 1950000 / 5078345
Processing transaction 1960000 / 5078345
Processing transaction 1970000 / 5078345
Processing transaction 1980000 / 5078345
Processing transaction 1990000 / 5078345
Processing transaction 2000000 / 5078345
Processing transaction 2010000 / 5078345
Processing transaction 2020000 / 5078345
Processing transaction 2030000 / 5078345
Processing transaction 2040000 / 5078345
Processing transaction 2050000 / 5078345
Processing transaction 2060000 / 5078345
Processing transaction 2070000 / 5078345
Processing transaction 2080000 / 5078345
Processing transaction 2090000 / 5078345
Processing transaction 2100000 / 5078345
Processing transaction 2110000 / 5078345
Processing transaction 2120000 / 5078345
Processing transaction 2130000 / 5078345
Processing transaction 2140000 / 5078345
Processing transaction 2150000 / 5078345
Processing transaction 2160000 / 5078345
Processing transaction 2170000 / 5078345
Processing transaction 2180000 / 5078345
Processing transaction 2190000 / 5078345
Processing transaction 2200000 / 5078345
Processing transaction 2210000 / 5078345
Processing transaction 2220000 / 5078345
Processing transaction 2230000 / 5078345
Processing transaction 2240000 / 5078345
Processing transaction 2250000 / 5078345
Processing transaction 2260000 / 5078345
Processing transaction 2270000 / 5078345
Processing transaction 2280000 / 5078345
Processing transaction 2290000 / 5078345
Processing transaction 2300000 / 5078345
Processing transaction 2310000 / 5078345
Processing transaction 2320000 / 5078345
Processing transaction 2330000 / 5078345
Processing transaction 2340000 / 5078345
Processing transaction 2350000 / 5078345
Processing transaction 2360000 / 5078345
Processing transaction 2370000 / 5078345
Processing transaction 2380000 / 5078345
Processing transaction 2390000 / 5078345
Processing transaction 2400000 / 5078345
Processing transaction 2410000 / 5078345
Processing transaction 2420000 / 5078345
Processing transaction 2430000 / 5078345
Processing transaction 2440000 / 5078345
Processing transaction 2450000 / 5078345
Processing transaction 2460000 / 5078345
Processing transaction 2470000 / 5078345
Processing transaction 2480000 / 5078345
Processing transaction 2490000 / 5078345
Processing transaction 2500000 / 5078345
Processing transaction 2510000 / 5078345
Processing transaction 2520000 / 5078345
Processing transaction 2530000 / 5078345
Processing transaction 2540000 / 5078345
Processing transaction 2550000 / 5078345
Processing transaction 2560000 / 5078345
Processing transaction 2570000 / 5078345
Processing transaction 2580000 / 5078345
Processing transaction 2590000 / 5078345
Processing transaction 2600000 / 5078345
Processing transaction 2610000 / 5078345
Processing transaction 2620000 / 5078345
Processing transaction 2630000 / 5078345
Processing transaction 2640000 / 5078345
Processing transaction 2650000 / 5078345
Processing transaction 2660000 / 5078345
Processing transaction 2670000 / 5078345
Processing transaction 2680000 / 5078345
Processing transaction 2690000 / 5078345
Processing transaction 2700000 / 5078345
Processing transaction 2710000 / 5078345
Processing transaction 2720000 / 5078345
Processing transaction 2730000 / 5078345
Processing transaction 2740000 / 5078345
Processing transaction 2750000 / 5078345
Processing transaction 2760000 / 5078345
Processing transaction 2770000 / 5078345
Processing transaction 2780000 / 5078345
Processing transaction 2790000 / 5078345
Processing transaction 2800000 / 5078345
Processing transaction 2810000 / 5078345
Processing transaction 2820000 / 5078345
Processing transaction 2830000 / 5078345
Processing transaction 2840000 / 5078345
Processing transaction 2850000 / 5078345
Processing transaction 2860000 / 5078345
Processing transaction 2870000 / 5078345
Processing transaction 2880000 / 5078345
Processing transaction 2890000 / 5078345
Processing transaction 2900000 / 5078345
Processing transaction 2910000 / 5078345
Processing transaction 2920000 / 5078345
Processing transaction 2930000 / 5078345
Processing transaction 2940000 / 5078345
Processing transaction 2950000 / 5078345
Processing transaction 2960000 / 5078345
Processing transaction 2970000 / 5078345
Processing transaction 2980000 / 5078345
Processing transaction 2990000 / 5078345
Processing transaction 3000000 / 5078345
Processing transaction 3010000 / 5078345
Processing transaction 3020000 / 5078345
Processing transaction 3030000 / 5078345
Processing transaction 3040000 / 5078345
Processing transaction 3050000 / 5078345
Processing transaction 3060000 / 5078345
Processing transaction 3070000 / 5078345
Processing transaction 3080000 / 5078345
Processing transaction 3090000 / 5078345
Processing transaction 3100000 / 5078345
Processing transaction 3110000 / 5078345
Processing transaction 3120000 / 5078345
Processing transaction 3130000 / 5078345
Processing transaction 3140000 / 5078345
Processing transaction 3150000 / 5078345
Processing transaction 3160000 / 5078345
Processing transaction 3170000 / 5078345
Processing transaction 3180000 / 5078345
Processing transaction 3190000 / 5078345
Processing transaction 3200000 / 5078345
Processing transaction 3210000 / 5078345
Processing transaction 3220000 / 5078345
Processing transaction 3230000 / 5078345
Processing transaction 3240000 / 5078345
Processing transaction 3250000 / 5078345
Processing transaction 3260000 / 5078345
Processing transaction 3270000 / 5078345
Processing transaction 3280000 / 5078345
Processing transaction 3290000 / 5078345
Processing transaction 3300000 / 5078345
Processing transaction 3310000 / 5078345
Processing transaction 3320000 / 5078345
Processing transaction 3330000 / 5078345
Processing transaction 3340000 / 5078345
Processing transaction 3350000 / 5078345
Processing transaction 3360000 / 5078345
Processing transaction 3370000 / 5078345
Processing transaction 3380000 / 5078345
Processing transaction 3390000 / 5078345
Processing transaction 3400000 / 5078345
Processing transaction 3410000 / 5078345
Processing transaction 3420000 / 5078345
Processing transaction 3430000 / 5078345
Processing transaction 3440000 / 5078345
Processing transaction 3450000 / 5078345
Processing transaction 3460000 / 5078345
Processing transaction 3470000 / 5078345
Processing transaction 3480000 / 5078345
Processing transaction 3490000 / 5078345
Processing transaction 3500000 / 5078345
Processing transaction 3510000 / 5078345
Processing transaction 3520000 / 5078345
Processing transaction 3530000 / 5078345
Processing transaction 3540000 / 5078345
Processing transaction 3550000 / 5078345
Processing transaction 3560000 / 5078345
Processing transaction 3570000 / 5078345
Processing transaction 3580000 / 5078345
Processing transaction 3590000 / 5078345
Processing transaction 3600000 / 5078345
Processing transaction 3610000 / 5078345
Processing transaction 3620000 / 5078345
Processing transaction 3630000 / 5078345
Processing transaction 3640000 / 5078345
Processing transaction 3650000 / 5078345
Processing transaction 3660000 / 5078345
Processing transaction 3670000 / 5078345
Processing transaction 3680000 / 5078345
Processing transaction 3690000 / 5078345
Processing transaction 3700000 / 5078345
Processing transaction 3710000 / 5078345
Processing transaction 3720000 / 5078345
Processing transaction 3730000 / 5078345
Processing transaction 3740000 / 5078345
Processing transaction 3750000 / 5078345
Processing transaction 3760000 / 5078345
Processing transaction 3770000 / 5078345
Processing transaction 3780000 / 5078345
Processing transaction 3790000 / 5078345
Processing transaction 3800000 / 5078345
Processing transaction 3810000 / 5078345
Processing transaction 3820000 / 5078345
Processing transaction 3830000 / 5078345
Processing transaction 3840000 / 5078345
Processing transaction 3850000 / 5078345
Processing transaction 3860000 / 5078345
Processing transaction 3870000 / 5078345
Processing transaction 3880000 / 5078345
Processing transaction 3890000 / 5078345
Processing transaction 3900000 / 5078345
Processing transaction 3910000 / 5078345
Processing transaction 3920000 / 5078345
Processing transaction 3930000 / 5078345
Processing transaction 3940000 / 5078345
Processing transaction 3950000 / 5078345
Processing transaction 3960000 / 5078345
Processing transaction 3970000 / 5078345
Processing transaction 3980000 / 5078345
Processing transaction 3990000 / 5078345
Processing transaction 4000000 / 5078345
Processing transaction 4010000 / 5078345
Processing transaction 4020000 / 5078345
Processing transaction 4030000 / 5078345
Processing transaction 4040000 / 5078345
Processing transaction 4050000 / 5078345
Processing transaction 4060000 / 5078345
Processing transaction 4070000 / 5078345
Processing transaction 4080000 / 5078345
Processing transaction 4090000 / 5078345
Processing transaction 4100000 / 5078345
Processing transaction 4110000 / 5078345
Processing transaction 4120000 / 5078345
Processing transaction 4130000 / 5078345
Processing transaction 4140000 / 5078345
Processing transaction 4150000 / 5078345
Processing transaction 4160000 / 5078345
Processing transaction 4170000 / 5078345
Processing transaction 4180000 / 5078345
Processing transaction 4190000 / 5078345
Processing transaction 4200000 / 5078345
Processing transaction 4210000 / 5078345
Processing transaction 4220000 / 5078345
Processing transaction 4230000 / 5078345
Processing transaction 4240000 / 5078345
Processing transaction 4250000 / 5078345
Processing transaction 4260000 / 5078345
Processing transaction 4270000 / 5078345
Processing transaction 4280000 / 5078345
Processing transaction 4290000 / 5078345
Processing transaction 4300000 / 5078345
Processing transaction 4310000 / 5078345
Processing transaction 4320000 / 5078345
Processing transaction 4330000 / 5078345
Processing transaction 4340000 / 5078345
Processing transaction 4350000 / 5078345
Processing transaction 4360000 / 5078345
Processing transaction 4370000 / 5078345
Processing transaction 4380000 / 5078345
Processing transaction 4390000 / 5078345
Processing transaction 4400000 / 5078345
Processing transaction 4410000 / 5078345
Processing transaction 4420000 / 5078345
Processing transaction 4430000 / 5078345
Processing transaction 4440000 / 5078345
Processing transaction 4450000 / 5078345
Processing transaction 4460000 / 5078345
Processing transaction 4470000 / 5078345
Processing transaction 4480000 / 5078345
Processing transaction 4490000 / 5078345
Processing transaction 4500000 / 5078345
Processing transaction 4510000 / 5078345
Processing transaction 4520000 / 5078345
Processing transaction 4530000 / 5078345
Processing transaction 4540000 / 5078345
Processing transaction 4550000 / 5078345
Processing transaction 4560000 / 5078345
Processing transaction 4570000 / 5078345
Processing transaction 4580000 / 5078345
Processing transaction 4590000 / 5078345
Processing transaction 4600000 / 5078345
Processing transaction 4610000 / 5078345
Processing transaction 4620000 / 5078345
Processing transaction 4630000 / 5078345
Processing transaction 4640000 / 5078345
Processing transaction 4650000 / 5078345
Processing transaction 4660000 / 5078345
Processing transaction 4670000 / 5078345
Processing transaction 4680000 / 5078345
Processing transaction 4690000 / 5078345
Processing transaction 4700000 / 5078345
Processing transaction 4710000 / 5078345
Processing transaction 4720000 / 5078345
Processing transaction 4730000 / 5078345
Processing transaction 4740000 / 5078345
Processing transaction 4750000 / 5078345
Processing transaction 4760000 / 5078345
Processing transaction 4770000 / 5078345
Processing transaction 4780000 / 5078345
Processing transaction 4790000 / 5078345
Processing transaction 4800000 / 5078345
Processing transaction 4810000 / 5078345
Processing transaction 4820000 / 5078345
Processing transaction 4830000 / 5078345
Processing transaction 4840000 / 5078345
Processing transaction 4850000 / 5078345
Processing transaction 4860000 / 5078345
Processing transaction 4870000 / 5078345
Processing transaction 4880000 / 5078345
Processing transaction 4890000 / 5078345

In [22]:
x = 0
i = 0
total = len(graph.graph.nodes)
for account in graph.graph.nodes:
    if i % 10 == 0:
        print(f"Processing account {i} / {total}")
    if i == 10000:
        break
    i += 1
    x = max(x, (graph.fast_get_money_cycled(account)))
print(x)

Processing account 0 / 515088
Processing account 10 / 515088
Processing account 20 / 515088
Processing account 30 / 515088
Processing account 40 / 515088
Processing account 50 / 515088
Processing account 60 / 515088
Processing account 70 / 515088
Processing account 80 / 515088
Processing account 90 / 515088
Processing account 100 / 515088
Processing account 110 / 515088
Processing account 120 / 515088
Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "/opt/anaconda3/envs/geo_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/2q/6vjsrj112rb774fzn79lb71h0000gn/T/ipykernel_91423/2608950392.py", line 10, in <module>
    x = max(x, (graph.fast_get_money_cycled(account)))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zeyaddaowd/Desktop/GP/LedgerDB/aml_service/graph/builder.py", line 101, in fast_get_money_cycled
    dfs(successor, account, self.LOOP_CUTOFF, 0, simple_paths, [])
  File "/Users/zeyaddaowd/Desktop/GP/LedgerDB/aml_service/graph/builder.py", line 94, in dfs
    dfs(v, target, path_length_threshold - 1, data['timestamp'], paths, current_path)
  File "/Users/zeyaddaowd/Desktop/GP/LedgerDB/aml_service/graph/builder.py", line 94, in dfs
    dfs(v, target, path_length_threshold - 1, data['timestamp'], paths, current_path)
  File "/Users/zeyaddaowd/Desktop/GP/LedgerDB/aml_service/graph/builder.py", line 94, in dfs
    dfs(v, target, path_length_threshold - 1, data['timestamp'], paths, current_path)
  File "/Users/zeyaddaowd/Desktop/GP/LedgerDB/aml_service/graph/builder.py", line None, in dfs
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/geo_env/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2201, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/geo_env/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1193, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/geo_env/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1064, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/geo_env/lib/python3.11/site-packages/IPython/core/ultratb.py", line 872, in structured_traceback
    formatted_exceptions: list[list[str]] = self.format_exception_as_a_whole(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/geo_env/lib/python3.11/site-packages/IPython/core/ultratb.py", line 784, in format_exception_as_a_whole
    frames.append(self.format_record(record))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/geo_env/lib/python3.11/site-packages/IPython/core/ultratb.py", line 540, in format_record
    assert isinstance(frame_info.lineno, int)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError